proj_name: gender-race-age-debias-text-encoder
train_text_encoder: True
train_unet: False
weight_loss_img: 8
weight_loss_face: 0.1
factor1_gender: 0.2
factor1_race: 0.6
factor1_age: 0.6
factor2_gender: 0.2
factor2_race: 0.3
factor2_age: 0.3
uncertainty_threshold: 0.2
train_images_per_prompt_GPU: 20
train_GPU_batch_size: 4
val_images_per_prompt_GPU: 24
val_GPU_batch_size: 8
learning_rate: 5e-5
max_train_steps: 15000