proj_name: race-debias-text-encoder
train_text_encoder: True
train_unet: False
weight_loss_img: 6
weight_loss_face: 0.1
factor1: 0.6
factor2: 0.3
uncertainty_threshold: 0.2
train_images_per_prompt_GPU: 16
train_GPU_batch_size: 4
val_images_per_prompt_GPU: 16
val_GPU_batch_size: 8
learning_rate: 5e-5
max_train_steps: 12000