proj_name: gender-race-debias-text-encoder-and-unet
train_text_encoder: True
train_unet: True
weight_loss_img: 8
weight_loss_face: 0.1
factor1_gender: 0.2
factor1_race: 0.6
factor2_gender: 0.2
factor2_race: 0.3
uncertainty_threshold: 0.2
train_images_per_prompt_GPU: 16
train_GPU_batch_size: 3
val_images_per_prompt_GPU: 24
val_GPU_batch_size: 8
learning_rate: 5e-5
max_train_steps: 15000