name: opensphere
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.7.4
  - pip
  - numpy=1.20.3
  - pillow=8.3.1
  - scipy=1.6.2
  - pytorch=1.9.0
  - cudatoolkit=11.1
  - pyyaml=5.3.1
  - libopencv=4.5.2
  - tabulate=0.8.9
  - scikit-image=0.17.2
  - scikit-learn=0.24.1
